graph TD
    Start --> a002
    Start --> a003

    a003[Look at the door] --> a004

    a002[Look at moss] --> a005
    a005[Use shovel on moss] --> a001
    a001[Gather moss] --> forest.mermaid{forest.mermaid}

    End